const moroccanCities = [
    "Agadir",
    "Aït Melloul",
    "Al Hoceïma",
    "Azrou",
    "Beni Mellal",
    "Berkane",
    "Casablanca",
    "El Jadida",
    "Fès",
    "Kenitra",
    "Khouribga",
    "Laâyoune",
    "Larache",
    "Marrakech",
    "Meknès",
    "Mohammedia",
    "Nador",
    "Oujda",
    "Rabat",
    "Safi",
    "Salé",
    "Settat",
    "Tanger",
    "Taourirt",
    "Taza",
    "Tétouan",
    "Tiznit",
    "Ouarzazate",
    "Essaouira",
    "Chefchaouen",
    "Ifrane",
    "Errachidia",
    "Guelmim",
    "Tan-Tan",
    "Dakhla"
];

export default moroccanCities;